import assert from "node:assert/strict";
import { after, test } from "node:test";
import { randomUUID } from "node:crypto";
import { PrismaClient } from "@prisma/client";
import { bindExternalEntity, importCalendar, assignFantasyWeek, recordOfficialScore } from "@/server/khl/data-layer";
import { importProtocols, importXg, setMembership } from "@/server/khl/observations";
import { hydratePlayers } from "@/server/khl/read-model";
import { enqueueKhl } from "@/server/khl/jobs";
import { runNextKhl } from "@/server/khl/coordinator";
import { importCatalog } from "@/server/khl/catalog-sync";
const db = new PrismaClient();
const enabled = process.env.KHL_TEST_DATABASE === "true" && process.env.DATABASE_URL?.includes("127.0.0.1:55439/khl_test");
after(() => db.$disconnect());
test("normalized KHL data: scope, replay, correction, membership and hydrated history", { skip: !enabled }, async () => {
  const football = async () => JSON.stringify(await Promise.all([db.coreLeague.findMany({ orderBy: { id: "asc" } }), db.coreTeam.findMany({ orderBy: { id: "asc" } }), db.corePlayer.findMany({ orderBy: { id: "asc" } }), db.coreMatch.findMany({ orderBy: { id: "asc" } }), db.fantasyContest.findMany({ orderBy: { id: "asc" } }), db.fantasyPlayerPrice.findMany({ orderBy: { id: "asc" } }), db.userFantasySquad.findMany({ orderBy: { id: "asc" } })]), (_k, v) => typeof v === "bigint" ? String(v) : v);
  const beforeFootball = await football();
  const key = randomUUID(), now = new Date();
  const competition = await db.khlCompetition.create({ data: { code: key } });
  const season = await db.khlSeason.create({ data: { competitionId: competition.id, seasonKey: key, label: "TEST" } });
  const contest = await db.khlContest.create({ data: { seasonId: season.id, providerContestId: key, name: "TEST" } });
  const batch = { contestId: contest.id, stageId: key, officialSeasonId: key, batchId: "calendar-1", observedAt: now, complete: true, matches: [{ eventId: key, officialMatchId: key, stageId: key, officialSeasonId: key, startsAt: new Date(now.getTime() - 86400000).toISOString(), home: { officialId: `${key}h`, mobileId: `${key}mh`, name: "Home" }, away: { officialId: `${key}a`, mobileId: `${key}ma`, name: "Away" }, status: "FINAL" as const, decidedBy: "REGULATION" as const, score: "2:1" }] };
  assert.equal((await importCalendar(db, batch)).changed, 1);
  assert.equal((await importCalendar(db, batch)).changed, 0);
  const match = await db.khlMatch.findFirstOrThrow({ where: { seasonId: season.id } });
  const player = await db.khlPlayer.create({ data: { name: "Test" } });
  const fantasy = await db.khlFantasyPlayer.create({ data: { contestId: contest.id, providerPlayerId: key, playerId: player.id, name: "Test", clubId: key, clubName: "Home", position: "F", currentPriceUnits: 500, observedAt: now } });
  await setMembership(db, { seasonId: season.id, playerId: player.id, teamId: match.homeId, startsAt: new Date(now.getTime() - 10 * 86400000), source: "TEST", observedAt: now });
  await setMembership(db, { seasonId: season.id, playerId: player.id, teamId: match.awayId, startsAt: new Date(now.getTime() + 86400000), source: "TEST", observedAt: now });
  assert.equal(await db.khlRosterMembership.count({ where: { playerId: player.id, endsAt: null } }), 1);
  await assert.rejects(db.$transaction(tx => bindExternalEntity(tx, { provider: "KHL", entityType: "team", providerScope: "global", externalId: `${key}h`, canonicalId: match.awayId, evidence: "bad", verifiedAt: now })), /MAPPING_CONFLICT/);
  const week = await db.khlFantasyWeek.create({ data: { contestId: contest.id, providerWeekId: "1", label: "One", sourceUrl: "TEST" } });
  await assignFantasyWeek(db, { contestId: contest.id, weekId: week.id, matchIds: [match.id], source: "TEST", observedAt: now, transitionKey: "1" });
  const protocol = { playerId: player.id, matchId: match.id, clubAtMatchId: match.homeId, participationStatus: "PLAYED" as const, toiSeconds: 601, ppToiSeconds: 61, pkToiSeconds: null, saves: null, goalsAgainst: null, goals: 1, assists: 0, plusMinus: 1, pimMinutes: 0, started: true, fullGame: null, shotsOnGoal: 3, shifts: 10, blockedShots: 0 };
  await importProtocols(db, { seasonId: season.id, source: "TEST", batchId: "1", observedAt: now, availableAt: now, rows: [protocol] });
  const xg = { seasonId: season.id, source: "TEST", definitionVersion: "1", batchId: "1", observedAt: now, availableAt: now, rows: [{ matchId: match.id, playerId: player.id, teamId: null, metric: "ixG", strength: "ALL", value: .4 }] };
  assert.equal((await importXg(db, xg)).changed, 1); assert.equal((await importXg(db, xg)).changed, 0);
  await importXg(db, { ...xg, batchId: "2", rows: [{ ...xg.rows[0], value: .7 }] });
  await recordOfficialScore(db, { contestId: contest.id, fantasyPlayerId: fantasy.id, matchId: match.id, points: 12, source: "TEST", observedAt: now, availableAt: now, transitionKey: "1" });
  const dto = (await hydratePlayers(db, [fantasy], { now }))[0];
  assert.equal(dto.toiSeconds.value, 601); assert.equal(dto.pkToiSeconds.value, null); assert.equal(dto.ixg.value, .7); assert.equal(dto.officialFp.value, 12);
  await assert.rejects(importProtocols(db, { seasonId: season.id, source: "TEST", batchId: "bad", observedAt: now, availableAt: now, rows: [{ ...protocol, ppToiSeconds: 900 }] }), /VALUES_INVALID/);
  assert.equal(await football(), beforeFootball, "KHL operations must not modify populated football/FPL tables");
  process.env.KHL_SYNC_ENABLED = "true";
  const job = await enqueueKhl(db, "TEST_COORDINATOR", key, "TEST");
  assert.equal((await runNextKhl(db, { "TEST_COORDINATOR:TEST": async () => { throw new Error("TEMPORARY_OUTAGE"); } }, job.id))?.status, "RETRY");
  await db.khlSyncJob.update({ where: { id: job.id }, data: { nextRunAt: new Date() } });
  assert.equal((await runNextKhl(db, { "TEST_COORDINATOR:TEST": async () => ({ page: 2 }) }, job.id))?.status, "DONE");
  assert.deepEqual((await db.khlProviderCheckpoint.findUniqueOrThrow({ where: { provider_scope_jobType: { provider: "TEST_COORDINATOR", scope: key, jobType: "TEST" } } })).cursor, { page: 2 });
  await assert.rejects(importCatalog(db, contest.id, [{ providerPlayerId: "test", providerTagId: null, name: "Test", clubId: "a", clubName: "A", position: "G", currentPriceUnits: 500, priceDelta: null, providerLock: false }], "bad-lease", now, false, { id: job.id, token: "expired" }), /LEASE_LOST/);
});
