/** @spec spec://modules/khl/INFRA-001-khl-data-ingestion#normalization */
import assert from 'node:assert/strict';
import {after,test} from 'node:test';
import {randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {PrismaClient} from '@prisma/client';
import {parseHockeyHistory} from '@/providers/sports-ru-hockey/history';
import {hockeyTeamLinks} from '@/providers/sports-ru-hockey/teams';
import {importCatalog} from '@/server/khl/catalog-sync';
import {importCalendar} from '@/server/khl/data-layer';
import {importHockeyHistory} from '@/server/khl/history-import';
import {hydratePlayers} from '@/server/khl/read-model';
const db=new PrismaClient();
const enabled=process.env.KHL_TEST_DATABASE==='true'&&process.env.DATABASE_URL?.includes('127.0.0.1:55439/khl_test');
after(()=>db.$disconnect());
test('public hockey history: exact matches, nulls, repeat and played-to-DNP correction',{skip:!enabled},async()=>{
 const key=randomUUID(),now=new Date('2026-09-08T12:00:00Z');
 const competition=await db.khlCompetition.create({data:{code:key}});
 const season=await db.khlSeason.create({data:{competitionId:competition.id,seasonKey:'2026/2027',label:'History fixture'}});
 const contest=await db.khlContest.create({data:{seasonId:season.id,providerContestId:'107',name:'History fixture'}});
 const profile=parseHockeyHistory(readFileSync('src/providers/sports-ru-hockey/fixtures/history-skater.html','utf8'),{tagId:'161159685',season:'2026/2027',position:'D'});
 await importCatalog(db,contest.id,[{providerPlayerId:'2167467',providerTagId:'161159685',name:profile.name,clubId:'3616',clubName:profile.club,position:'D',currentPriceUnits:500,priceDelta:null,providerLock:false}],key,now,true);
 const team=(slug:string)=>{const t=hockeyTeamLinks.find(t=>t[2]===slug)!;return {officialId:t[1],mobileId:key+t[1],name:slug};};
 const matches=profile.rows.map((r,i)=>({eventId:key+i,officialMatchId:key+i,stageId:key,officialSeasonId:key,startsAt:r.date+'T12:00:00Z',home:team(r.home?profile.clubSlug:r.opponentSlug),away:team(r.home?r.opponentSlug:profile.clubSlug),status:'FINAL' as const,decidedBy:'REGULATION' as const,score:r.score!}));
 await importCalendar(db,{contestId:contest.id,stageId:key,officialSeasonId:key,matches,batchId:key,observedAt:now,complete:true});
 const player=await db.khlFantasyPlayer.findFirstOrThrow({where:{contestId:contest.id}});
 const input={contestId:contest.id,fantasyPlayerId:player.id,profile,source:'https://www.sports.ru/fantasy/hockey/player/info/107/2167467.html',observedAt:now};
 assert.equal((await importHockeyHistory(db,input)).played,2);
 const revisions=()=>db.khlObservationRevision.count({where:{OR:[{streamId:{startsWith:`SPORTS_RU:history:${player.id}:`}},{streamId:{startsWith:`official-fp:${contest.id}:`}}]}});
 const count=await revisions();
 assert.equal((await importHockeyHistory(db,input)).changed,0);
 assert.equal(await revisions(),count);
 const dto=(await hydratePlayers(db,[player],{now}))[0];assert.equal(dto.officialFp.value,12);assert.equal(dto.toiSeconds.value,1130);assert.equal(dto.ppToiSeconds.value,null);
 const corrected=structuredClone(profile);corrected.rows[0]={...corrected.rows[0],toiSeconds:0,goals:0,assists:0,pimMinutes:0,plusMinus:0,points:0};
 assert.equal((await importHockeyHistory(db,{...input,profile:corrected})).dnp,1);
 assert.equal(await db.khlOfficialFantasyScore.count({where:{fantasyPlayerId:player.id}}),1);
 const mismatch=structuredClone(profile);mismatch.rows[0].score='99:99';
 assert.equal((await importHockeyHistory(db,{...input,profile:mismatch})).quarantined.length,1);
 await assert.rejects(importHockeyHistory(db,{...input,source:input.source.replace('2167467','1')}),/SCOPE_INVALID/);
});
