/** @spec spec://modules/khl/INFRA-001-khl-data-ingestion#normalization */
import assert from 'node:assert/strict';
import {after,test} from 'node:test';
import {randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {PrismaClient} from '@prisma/client';
import {parseHockeyHistory} from '@/providers/sports-ru-hockey/history';
import {hockeyTeamLinks} from '@/providers/sports-ru-hockey/teams';
import {importCatalog} from '@/server/khl/catalog-sync';
import {importCalendar} from '@/server/khl/data-layer';
import {importHockeyHistory} from '@/server/khl/history-import';
import {importProtocols} from '@/server/khl/observations';
import {publishRollingForecast} from '@/server/khl/rolling-forecast';
import {hydratePlayers} from '@/server/khl/read-model';
const db=new PrismaClient();
const enabled=process.env.KHL_TEST_DATABASE==='true'&&Boolean(process.env.DATABASE_URL?.match(/127\.0\.0\.1:(55439|45439)\/khl_test/));
after(()=>db.$disconnect());
test('public hockey history: exact matches, nulls, repeat and played-to-DNP correction',{skip:!enabled},async()=>{
 const key=randomUUID(),now=new Date('2026-09-08T12:00:00Z');
 const competition=await db.khlCompetition.create({data:{code:key}});
 const season=await db.khlSeason.create({data:{competitionId:competition.id,seasonKey:'2026/2027',label:'History fixture'}});
 const contest=await db.khlContest.create({data:{seasonId:season.id,providerContestId:'107',name:'History fixture'}});
 const profile=parseHockeyHistory(readFileSync('src/providers/sports-ru-hockey/fixtures/history-skater.html','utf8'),{tagId:'161159685',season:'2026/2027',position:'D'});
 await importCatalog(db,contest.id,[{providerPlayerId:'2167467',providerTagId:'161159685',name:profile.name,clubId:'3616',clubName:profile.club,position:'D',currentPriceUnits:500,priceDelta:null,providerLock:false}],key,now,true);
 const team=(slug:string)=>{const t=hockeyTeamLinks.find(t=>t[2]===slug)!;return {officialId:t[1],mobileId:key+t[1],name:slug};};
 const matches=profile.rows.map((r,i)=>({eventId:key+i,officialMatchId:key+i,stageId:key,officialSeasonId:key,startsAt:r.date+'T12:00:00Z',home:team(r.home?profile.clubSlug:r.opponentSlug),away:team(r.home?r.opponentSlug:profile.clubSlug),status:'FINAL' as const,decidedBy:'REGULATION' as const,score:r.score!}));
 await importCalendar(db,{contestId:contest.id,stageId:key,officialSeasonId:key,matches,batchId:key,observedAt:now,complete:true});
 const player=await db.khlFantasyPlayer.findFirstOrThrow({where:{contestId:contest.id}});
 const input={contestId:contest.id,fantasyPlayerId:player.id,profile,source:'https://www.sports.ru/fantasy/hockey/player/info/107/2167467.html',observedAt:now};
 assert.equal((await importHockeyHistory(db,input)).played,2);
 const revisions=()=>db.khlObservationRevision.count({where:{OR:[{streamId:{startsWith:`SPORTS_RU:history:${player.id}:`}},{streamId:{startsWith:`official-fp:${contest.id}:`}}]}});
 const count=await revisions();
 assert.equal((await importHockeyHistory(db,input)).changed,0);
 assert.equal(await revisions(),count);
 const dto=(await hydratePlayers(db,[player],{now}))[0];assert.equal(dto.officialFp.value,12);assert.equal(dto.toiSeconds.value,1130);assert.equal(dto.ppToiSeconds.value,null);

 // @spec spec://modules/khl/INFRA-002-khl-storage-and-api#protocol-aggregates
 const stats=await db.khlPlayerMatchStat.findMany({where:{playerId:player.playerId!,match:{seasonId:season.id}},orderBy:{match:{startsAt:'asc'}}});
 const first=stats[0];
 const protocol={playerId:first.playerId,matchId:first.matchId,clubAtMatchId:first.clubAtMatchId!,participationStatus:'PLAYED' as const,toiSeconds:first.toiSeconds,ppToiSeconds:300,pkToiSeconds:60,attackZoneSeconds:120,goals:first.goals,assists:first.assists,plusMinus:first.plusMinus,pimMinutes:first.pimMinutes,shotsOnGoal:3,saves:null,goalsAgainst:null,shifts:20,blockedShots:2,started:null,fullGame:null};
 const fullInput={seasonId:season.id,source:'https://www.khl.ru/game/1436/901980/protocol/',batchId:randomUUID(),observedAt:now,availableAt:now,rows:[protocol]};
 const concurrent=await Promise.all([importHockeyHistory(db,input),importProtocols(db,fullInput)]);
 assert.equal(concurrent[1].changed,1);
 assert.equal((await importProtocols(db,{...fullInput,batchId:randomUUID()})).changed,0);
 assert.equal(await db.khlPlayerMatchStat.count({where:{playerId:player.playerId!,match:{seasonId:season.id}}}),2);
 const seasonDto=(await hydratePlayers(db,[player],{now}))[0];
 assert.equal(seasonDto.seasonStats!.games,2);
 assert.deepEqual(seasonDto.seasonStats!.totals.attackZoneSeconds,{value:120,knownGames:1});
 assert.equal(seasonDto.ppToiSeconds.value,300);
 assert.equal(seasonDto.ppToiSeconds.knownGames,1);
 assert.equal(seasonDto.ppToiSeconds.totalGames,2);
 assert.equal(seasonDto.attackZoneSeconds?.value,120);
 await importProtocols(db,{...fullInput,batchId:randomUUID(),rows:[{...protocol,attackZoneSeconds:90}]});
 await importHockeyHistory(db,input);
 const afterCorrection=(await hydratePlayers(db,[player],{now}))[0];
 assert.equal(afterCorrection.seasonStats!.totals.attackZoneSeconds.value,90);
 assert.equal(afterCorrection.seasonStats!.totals.ppToiSeconds.value,300);
 await importProtocols(db,{...fullInput,batchId:randomUUID(),rows:[{...protocol,pkToiSeconds:0,attackZoneSeconds:90}]});
 const zeroKnown=(await hydratePlayers(db,[player],{now}))[0];
 assert.equal(zeroKnown.pkToiSeconds.value,0);
 assert.equal(zeroKnown.pkToiSeconds.quality,'FACT');
 assert.equal(zeroKnown.pkToiSeconds.knownGames,1);
 assert.equal(zeroKnown.pkToiSeconds.totalGames,2);
 // @spec spec://modules/khl/FEAT-003-khl-projections-and-optimizer#rolling-beta
 const future={...matches[0],eventId:key+'future',officialMatchId:key+'future',startsAt:'2026-09-09T12:00:00Z',status:'SCHEDULED' as const,score:null};
 const beyond={...future,eventId:key+'beyond',officialMatchId:key+'beyond',startsAt:'2026-09-17T12:00:00Z'};
 await importCalendar(db,{contestId:contest.id,stageId:key,officialSeasonId:key,matches:[...matches,future,beyond],batchId:randomUUID(),observedAt:now,complete:true,from:new Date('2026-09-01T00:00:00Z'),to:new Date('2026-09-20T00:00:00Z')});
 const forecast=await publishRollingForecast(db,contest.id,now);
 assert.equal((await publishRollingForecast(db,contest.id,now)).id,forecast.id);
 const projected=(await hydratePlayers(db,[player],{now}))[0];
 assert.equal(projected.ep.quality,'ESTIMATE'); assert.equal(projected.ep.value,12);
 assert.equal(projected.fixtures.filter(f=>f.expectedPoints?.value!==null).length,1);
 assert.equal(projected.ixg.value,null);
 const late=(await hydratePlayers(db,[player],{now:new Date(now.getTime()+3600001)}))[0];
 assert.equal(late.ep.value,null);

 const futureMatch=await db.khlMatch.findFirstOrThrow({where:{seasonId:season.id,startsAt:new Date(future.startsAt)}});
 const protectedWeek=await db.khlFantasyWeek.create({data:{contestId:contest.id,providerWeekId:'protected',label:'Protected week',sourceUrl:'TEST',verified:true,startsAt:new Date('2026-09-08T00:00:00Z'),endsAt:new Date('2026-09-15T00:00:00Z'),timezone:'Europe/Moscow'}});
 await db.khlMatchFantasyWeek.create({data:{contestId:contest.id,matchId:futureMatch.id,weekId:protectedWeek.id}});
 const conflicting=structuredClone(profile);conflicting.fixtures=[{...profile.rows[0],date:'2026-09-09',week:2,score:null}];
 const isolated=await importHockeyHistory(db,{...input,profile:conflicting});
 assert.ok(isolated.quarantined.includes(`WEEK_ASSIGNMENT_CONFLICT:${futureMatch.id}`));
 assert.equal(isolated.played,2);
 assert.equal((await db.khlMatchFantasyWeek.findUniqueOrThrow({where:{contestId_matchId:{contestId:contest.id,matchId:futureMatch.id}}})).weekId,protectedWeek.id);

 const corrected=structuredClone(profile);corrected.rows[0]={...corrected.rows[0],toiSeconds:0,goals:0,assists:0,pimMinutes:0,plusMinus:0,points:0};
 assert.equal((await importHockeyHistory(db,{...input,profile:corrected})).dnp,1);
 assert.equal(await db.khlOfficialFantasyScore.count({where:{fantasyPlayerId:player.id}}),1);
 const mismatch=structuredClone(profile);mismatch.rows[0].score='99:99';
 assert.equal((await importHockeyHistory(db,{...input,profile:mismatch})).quarantined.length,1);
 await assert.rejects(importHockeyHistory(db,{...input,source:input.source.replace('2167467','1')}),/SCOPE_INVALID/);
});
