import assert from "node:assert/strict";
import { after, test } from "node:test";
import { createHash, randomUUID } from "node:crypto";
import { prisma } from "@/lib/db";
import { sessionCookieName } from "@/lib/auth-constants";
import { appendRevision } from "./repositories/revisions";
import { importCatalog } from "@/server/khl/catalog-sync";
import { enqueueKhl, claimKhlJob, finishKhlJob } from "@/server/khl/jobs";
import { GET, POST, PUT } from "@/app/api/machete/khl/[...path]/route";
import { createTransferPreview, saveTransferPlan } from "@/server/khl/transfer-plans";
import { storeKhlRaw } from "@/server/khl/retention";
const enabled = process.env.KHL_TEST_DATABASE === "true" && process.env.DATABASE_URL?.includes("127.0.0.1:55439/khl_test");
after(async () => { await prisma.$disconnect(); });
test("DB-01/02 API-01/02: KHL isolation, transition history, leases and save race", { skip: !enabled }, async () => {
  process.env.KHL_ENABLED = "true"; process.env.KHL_SYNC_ENABLED = "true";
  const prefix = randomUUID();
  const user = await prisma.user.create({ data: { email: `khl-${prefix}@example.test`, role: "USER", franchise: "MACHETE" } });
  const originalUser = JSON.stringify(user);
  const token = randomUUID();
  await prisma.userSession.create({ data: { userId: user.id, tokenHash: createHash("sha256").update(token).digest("hex"), expiresAt: new Date(Date.now() + 600000) } });
  const competition = await prisma.khlCompetition.create({ data: { code: prefix } });
  const season = await prisma.khlSeason.create({ data: { competitionId: competition.id, seasonKey: "test", label: "TEST" } });
  const contest = await prisma.khlContest.create({ data: { seasonId: season.id, providerContestId: "107", name: "KHL TEST" } });
  const row = { providerPlayerId: "1", providerTagId: "2", name: "Test", clubId: "3", clubName: "Test club", position: "G" as const, currentPriceUnits: 500, priceDelta: null, providerLock: false };
  const t = Date.now();
  await importCatalog(prisma, contest.id, [row], "A1", new Date(t));
  await importCatalog(prisma, contest.id, [row], "A2", new Date(t + 1));
  await importCatalog(prisma, contest.id, [{ ...row, currentPriceUnits: 600 }], "B", new Date(t + 2));
  await importCatalog(prisma, contest.id, [row], "A3", new Date(t + 3));
  const streamId = `SPORTS_RU:catalog:${contest.id}:1`;
  assert.equal(await prisma.khlObservationRevision.count({ where: { streamId } }), 3);
  const history = await prisma.khlObservationRevision.findMany({ where: { streamId }, orderBy: { sequence: "asc" } });
  assert.deepEqual(history.map(r => (r.value as { currentPriceUnits: number }).currentPriceUnits), [500, 600, 500]);
  await prisma.$transaction(tx => appendRevision(tx, { streamId, transitionKey: "A2", value: row, observedAt: new Date(t + 1) }));
  assert.equal(await prisma.khlObservationRevision.count({ where: { streamId } }), 3);
  await assert.rejects(prisma.$transaction(tx => appendRevision(tx, { streamId, transitionKey: "A2", value: { ...row, currentPriceUnits: 999 }, observedAt: new Date(t + 1) })), /IDEMPOTENCY_CONFLICT/);
  const jobs = await Promise.all([enqueueKhl(prisma, "TEST", prefix, "CATALOG"), enqueueKhl(prisma, "TEST", prefix, "CATALOG")]);
  assert.equal(jobs[0].id, jobs[1].id);
  const claimed = await Promise.all([claimKhlJob(prisma, jobs[0].id), claimKhlJob(prisma, jobs[0].id)]);
  assert.equal(claimed.filter(Boolean).length, 1);
  const job = claimed.find(Boolean)!;
  assert.equal((await finishKhlJob(prisma, job.id, "wrong")).count, 0);
  assert.equal((await finishKhlJob(prisma, job.id, job.leaseToken)).count, 1);
  const player = await prisma.khlFantasyPlayer.findFirstOrThrow({ where: { contestId: contest.id } });
  const req = (method: string, route: string, body?: unknown, cookie = token) => new Request(`http://localhost/api/machete/khl/${route}`, { method, headers: { origin: "http://localhost", cookie: `${sessionCookieName}=${cookie}`, "content-type": "application/json" }, ...(body ? { body: JSON.stringify(body) } : {}) });
  const body = { contestId: contest.id, name: "Draft", bankUnits: null, entries: [{ id: player.id, keepForOptimizer: true }], mode: "DRAFT" };
  const create = await POST(req("POST", "squads", body), { params: Promise.resolve({ path: ["squads"] }) });
  assert.equal(create.status, 200, await create.clone().text());
  const saved = (await create.json()).data;
  const crossOrigin = req("POST", "squads", body);
  crossOrigin.headers.set("origin", "https://unrelated.example");
  assert.equal((await POST(crossOrigin, { params: Promise.resolve({ path: ["squads"] }) })).status, 403);
  const edits = await Promise.all([1, 2].map(() => PUT(req("PUT", `squads/${saved.id}`, { ...body, expectedVersion: 1 }), { params: Promise.resolve({ path: ["squads", saved.id] }) })));
  assert.deepEqual(edits.map(r => r.status).sort(), [200, 409]);
  const foreignUser = await prisma.user.create({ data: { email: `foreign-${prefix}@example.test` } });
  const foreignSquad = await prisma.khlUserSquad.create({ data: { userId: foreignUser.id, contestId: contest.id, name: "Private" } });
  assert.equal((await GET(req("GET", `squads/${foreignSquad.id}?contestId=${contest.id}`), { params: Promise.resolve({ path: ["squads", foreignSquad.id] }) })).status, 404);
  process.env.KHL_ENABLED = "false";
  assert.equal((await GET(req("GET", "contests"), { params: Promise.resolve({ path: ["contests"] }) })).status, 404);
  process.env.KHL_ENABLED = "true";
  assert.equal(JSON.stringify(await prisma.user.findUnique({ where: { id: user.id } })), originalUser);
  const transferRows = Array.from({ length: 18 }, (_, i) => ({ ...row, providerTagId: `${prefix}-${i}`, providerPlayerId: `transfer${i}`, clubId: `club${i % 7}`, currentPriceUnits: 1000, position: i < 2 ? "G" as const : i < 8 ? "D" as const : "F" as const }));
  await assert.rejects(importCatalog(prisma, contest.id, transferRows.map(p => ({ ...p, providerTagId: "duplicated-tag" })), "bad-identities", new Date()), /DUPLICATE_PROVIDER_IDENTITY/);
  await importCatalog(prisma, contest.id, transferRows, "transfer-batch", new Date());
  const transferPlayers = await prisma.khlFantasyPlayer.findMany({ where: { contestId: contest.id, providerPlayerId: { startsWith: "transfer" } } });
  const playerByIndex = (i: number) => transferPlayers.find(p => p.providerPlayerId === `transfer${i}`)!;
  const transferSquad = await prisma.khlUserSquad.create({ data: { userId: user.id, contestId: contest.id, name: "Transfers", bankUnits: 3000 } });
  await prisma.khlUserSquadEntry.createMany({ data: Array.from({ length: 17 }, (_, i) => ({ squadId: transferSquad.id, contestId: contest.id, fantasyPlayerId: playerByIndex(i).id, slotIndex: i })) });
  const week = await prisma.khlFantasyWeek.create({ data: { contestId: contest.id, providerWeekId: "1", label: "Unverified test", sourceUrl: "test://synthetic" } });
  const quote = await createTransferPreview(prisma, user.id, transferSquad.id, contest.id, { weekId: week.id, expectedVersion: 1, steps: [{ out: playerByIndex(16).id, in: playerByIndex(17).id }] });
  const planBody = { quoteHash: quote.quoteHash, expectedVersion: 1 };
  const plan = await saveTransferPlan(prisma, user.id, transferSquad.id, contest.id, planBody, "save-one");
  const repeatedPlan = await saveTransferPlan(prisma, user.id, transferSquad.id, contest.id, planBody, "save-one");
  assert.equal(plan.id, repeatedPlan.id);
  assert.equal(plan.externalExecuted, false);
  assert.equal((await prisma.khlUserSquad.findUniqueOrThrow({ where: { id: transferSquad.id } })).revision, 2);
  await assert.rejects(saveTransferPlan(prisma, user.id, transferSquad.id, contest.id, { ...planBody, expectedVersion: 2 }, "save-one"), /Idempotency-Key/);
  const staleQuote = await createTransferPreview(prisma, user.id, transferSquad.id, contest.id, { weekId: week.id, expectedVersion: 2, steps: [{ out: playerByIndex(17).id, in: playerByIndex(16).id }] });
  await prisma.khlContest.update({ where: { id: contest.id }, data: { revision: { increment: 1 } } });
  await assert.rejects(saveTransferPlan(prisma, user.id, transferSquad.id, contest.id, { quoteHash: staleQuote.quoteHash, expectedVersion: 2 }, "stale"), /Цены или статусы/);
  const rawInput = { provider: "TEST", scope: prefix, parserVersion: "1", raw: Buffer.from("sample"), now: new Date() };
  assert.equal(await storeKhlRaw(prisma, rawInput), await storeKhlRaw(prisma, rawInput));
});
