const flagByCountryName: Record<string, string> = {
  algeria: "🇩🇿",
  argentina: "🇦🇷",
  australia: "🇦🇺",
  austria: "🇦🇹",
  belgium: "🇧🇪",
  "bosnia and herzegovina": "🇧🇦",
  brazil: "🇧🇷",
  canada: "🇨🇦",
  "cape verde": "🇨🇻",
  colombia: "🇨🇴",
  croatia: "🇭🇷",
  curacao: "🇨🇼",
  "czech republic": "🇨🇿",
  "dr congo": "🇨🇩",
  ecuador: "🇪🇨",
  egypt: "🇪🇬",
  england: "\u{1F3F4}\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}",
  france: "🇫🇷",
  germany: "🇩🇪",
  ghana: "🇬🇭",
  haiti: "🇭🇹",
  iran: "🇮🇷",
  iraq: "🇮🇶",
  "ivory coast": "🇨🇮",
  japan: "🇯🇵",
  jordan: "🇯🇴",
  mexico: "🇲🇽",
  morocco: "🇲🇦",
  netherlands: "🇳🇱",
  "new zealand": "🇳🇿",
  norway: "🇳🇴",
  panama: "🇵🇦",
  paraguay: "🇵🇾",
  portugal: "🇵🇹",
  qatar: "🇶🇦",
  "saudi arabia": "🇸🇦",
  scotland: "\u{1F3F4}\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}",
  senegal: "🇸🇳",
  "south africa": "🇿🇦",
  "south korea": "🇰🇷",
  spain: "🇪🇸",
  sweden: "🇸🇪",
  switzerland: "🇨🇭",
  tunisia: "🇹🇳",
  turkey: "🇹🇷",
  "united states": "🇺🇸",
  uruguay: "🇺🇾",
  uzbekistan: "🇺🇿"
};

export function nationalTeamFlag(teamName: string): string | null {
  return flagByCountryName[teamName.trim().toLowerCase()] ?? null;
}
